GET http://localhost:3003/api/blogs
Content-Type: application/json
###


POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "El Jorobado de Notre Dam",
  "author": "Félix Redondo",
  "url": "https://yoloindahouse.com",
  "likes": 288
}
###
